# Generated by Django 2.2.3 on 2019-10-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('carrera', models.CharField(choices=[('IS', 'Ingenieria en Sistemas'), ('IE', 'Ingenieria en Electronica'), ('IT', 'Ingenieria en Telecomunicaciones'), ('IC', 'Ingenieria Civil')], max_length=5)),
                ('semestre', models.CharField(choices=[('2S', 'Segundo semestre'), ('4S', 'Cuarto semestre'), ('6S', 'Sexto semestre'), ('8S', 'Octavo semestre')], max_length=5)),
                ('seccion', models.CharField(choices=[('A', 'Seccion A'), ('B', 'Seccion B'), ('C', 'Seccion C'), ('D', 'Seccion D'), ('E', 'Seccion E')], max_length=5)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.IntegerField()),
                ('nombre1', models.CharField(max_length=20)),
                ('nombre2', models.CharField(blank=True, max_length=20)),
                ('nombre3', models.CharField(blank=True, max_length=50)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20)),
                ('actividad', models.CharField(choices=[('Ng', 'Ninguna'), ('Vj', 'Videojuegos'), ('Rg', 'Robogallitos'), ('Pp', 'Presentacion de Proyectos'), ('Ex', 'Exposicion'), ('St', 'Staff')], max_length=4)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citein.Grado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
